Release v0.13.0
wikimedia/stylelint-config-wikimedia pull request #179
Opened 2022-04-29 18:22 UTC by jdforrester

2022-04-29 21:23 UTC, edg2s approved these changes

2022-05-02 10:46 UTC, edg2s requested changes
Some more PRs are pending that we should include in the release.

2022-05-03 21:03 UTC, Volker-E commented
I'd like to remove 'grade-a/grade-c.json' as well for this

2022-05-04 14:12 UTC, edg2s commented
Will test against a few repos first.

2022-05-04 20:25 UTC, edg2s approved these changes

2022-05-04 20:37 UTC, merged